server:
  port: 8000

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: con-2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.common.dto
        spring.json.value.default.type: com.common.dto.UserDto
        spring.json.use.type.headers: false